FRNT- 498 create demo with forms and woly components
woly-ui/demo pull request #3
Opened 2021-05-28 13:24 UTC by Irinaristova

2021-06-02 10:20 UTC, sergeysova requested changes
Зафиксишь сборку?
https://github.com/woly-ui/demo/pull/3/checks?check_run_id=2694609658

2021-06-07 14:15 UTC, sergeysova approved these changes

2021-08-02 12:30 UTC, purplecandle commented on .eslintrc
> +        "@eslint-kit/prettier",
```suggestion
        "@eslint-kit/react",
```
Этих пакетов нет в зависимостях

2021-08-02 12:30 UTC, purplecandle commented on .eslintrc
> +                ],
```suggestion
```
Неиспользуемый alias

2021-08-02 12:30 UTC, purplecandle commented on .gitignore
> +public/
У нас razzle, public используется

2021-08-02 12:30 UTC, purplecandle commented on .editorconfig
> +max_line_length = 80
```suggestion
max_line_length = 100
```
**suggestion:** В .prettierrc у нас стоит 100

2021-08-04 12:21 UTC, purplecandle approved these changes

2021-08-04 12:22 UTC, merged